src/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/students/urls.py
from django.urls import path

from . import views

app_name = "students"
urlpatterns = [
    path("", views.index, name="index"),
    path("multiple_choice/", views.multiple_choice, name="multiple_choice"),
    path("true_false/", views.true_false, name="true_false"),
    path("writing/", views.writing, name="writing"),
    path("matching/", views.matching, name="matching"),
    path("get_flashcards/", views.get_flashcards, name="get_flashcards"),
    path("update_results/", views.update_results, name="update_results"),
    path("student_data/<int:id>/", views.student_data, name="student_data"),
]

src/teachers/urls.py
from django.urls import path

from . import views

app_name = "teachers"
urlpatterns = [
    path("", views.index, name="index"),
    path("assignment/", views.assignment, name="assignment"),
    path("assignment_flashcards/", views.assignment_flashcards, name="assignment_flashcards"),
    path("search/", views.search, name="search"),
    path("search_flashcards/", views.search_flashcards, name="search_flashcards"),
    path("search_students/", views.search_students, name="search_students"),
    path("search_decks/", views.search_decks, name="search_decks"),
    path("student/<int:id>/", views.student, name="student"),
    path("student_data/<int:id>/", views.student_data, name="student_data"),
    path("deck/<int:id>/", views.deck, name="deck"),
    path("students/", views.students, name="students"),
    path("students_student/", views.students_student, name="students_student"),
    path("new_deck/", views.new_deck, name="new_deck"),
    path("deck_flashcards/<int:id>/", views.deck_flashcards, name="deck_flashcards"),
    path("edit_deck/<int:id>/", views.edit_deck, name="edit_deck"),
    path("delete_deck/<int:id>/", views.delete_deck, name="delete_deck"),
]

src/users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

src/students/models.py
from django.db import models

# Create your models here.

src/teachers/models.py
from django.db import models

# Create your models here.

src/students/views.py
from django.core.files.storage import default_storage
from django.http import JsonResponse
from django.shortcuts import render, redirect
import json

from users.models import Flashcard, Student, Teacher, Deck, Result


def login_required(view_func):
    def _wrapped_view(request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("users:login")
        elif request.session.get("role") == "teacher":
            return redirect("teachers:index")
        elif request.session.get("role") == "student":
            return view_func(request, *args, **kwargs)
        else:
            return redirect("users:index")

    return _wrapped_view


# Create your views here.
@login_required
def index(request):
    student = Student.objects.get(user=request.user)
    results = Result.objects.filter(student=student)

    new_cards = results.filter(state=Result.NEW_CARDS).count()
    still_learning = results.filter(state=Result.STILL_LEARNING).count()
    almost_done = results.filter(state=Result.ALMOST_DONE).count()
    mastered = results.filter(state=Result.MASTERED).count()

    all_flashcards = new_cards + still_learning + almost_done + mastered
    score = 0
    if all_flashcards > 0:
        score = int(
            (still_learning / all_flashcards) * 25
            + (almost_done / all_flashcards) * 75
            + (mastered / all_flashcards) * 100
        )

    return render(
        request,
        "students/index.html",
        {
            "student": student,
            "results": results,
            "new_cards": new_cards,
            "still_learning": still_learning,
            "almost_done": almost_done,
            "mastered": mastered,
            "score": score,
        },
    )


@login_required
def multiple_choice(request):
    return render(request, "students/multiple_choice.html")


@login_required
def true_false(request):
    return render(request, "students/true_false.html")


@login_required
def writing(request):
    return render(request, "students/writing.html")


@login_required
def matching(request):
    return render(request, "students/matching.html")


@login_required
def get_flashcards(request):
    student = Student.objects.get(user=request.user)
    results = Result.objects.filter(student=student)
    results_list = []

    for result in results:
        flashcard = result.flashcard
        results_list.append(
            {
                "flashcard__id": flashcard.id,
                "flashcard__front": flashcard.front,
                "flashcard__back": flashcard.back,
                "flashcard__image": default_storage.url(str(flashcard.image)),
                "state": result.state,
            }
        )

    return JsonResponse({"flashcards": results_list})


@login_required
def update_results(request):
    student = Student.objects.get(user=request.user)

    if request.method == "POST":
        flashcards = json.loads(request.body).get("flashcards")

        for flashcard_data in flashcards:
            try:
                flashcard = Flashcard.objects.get(id=flashcard_data["flashcard__id"])
                result = Result.objects.get(student=student, flashcard=flashcard)
                result.state = flashcard_data["state"]
                result.save()
            except Result.DoesNotExist:
                continue

    return JsonResponse({"message": "Results updated successfully."})


@login_required
def student_data(request, id):
    student = Student.objects.get(user=request.user)
    results = Result.objects.filter(student=student)

    new_cards = results.filter(state=Result.NEW_CARDS).count()
    still_learning = results.filter(state=Result.STILL_LEARNING).count()
    almost_done = results.filter(state=Result.ALMOST_DONE).count()
    mastered = results.filter(state=Result.MASTERED).count()

    return JsonResponse({
        "new_cards": new_cards,
        "still_learning": still_learning,
        "almost_done": almost_done,
        "mastered": mastered,
    })

src/teachers/views.py
from django.core.files.storage import default_storage
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from users.models import Flashcard, Student, Teacher, Deck, Result


def login_required(view_func):
    def _wrapped_view(request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("users:login")
        elif request.session.get("role") == "teacher":
            return view_func(request, *args, **kwargs)
        elif request.session.get("role") == "student":
            return redirect("students:index")
        else:
            return redirect("users:index")

    return _wrapped_view


# Create your views here.
@login_required
def index(request):
    return redirect("teachers:assignment")


@login_required
def assignment(request):
    teacher = Teacher.objects.get(user=request.user)
    flashcards = teacher.flashcards.all()

    return render(request, "teachers/assignment.html", {"flashcards": flashcards})


@login_required
def assignment_flashcards(request):
    teacher = Teacher.objects.get(user=request.user)

    if request.method == "POST":
        flashcard_id = request.POST.get("flashcard_id")
        flashcard = Flashcard.objects.get(id=flashcard_id)
        action = request.POST.get("action")

        if action == "add":
            teacher.add_flashcard(flashcard)
        elif action == "remove":
            teacher.remove_flashcard(flashcard)

    flashcards = teacher.flashcards.all()
    flashcards_list = list(flashcards.values("id", "front", "back", "image"))
    for flashcard in flashcards_list:
        if flashcard["image"]:
            flashcard["image_url"] = default_storage.url(str(flashcard["image"]))
        else:
            flashcard["image_url"] = None

    return JsonResponse({"flashcards": flashcards_list})


@login_required
def search(request):
    return render(request, "teachers/search.html")


@login_required
def search_flashcards(request):
    query = request.GET.get("query", "")
    flashcards_list = []

    if query:
        flashcards = Flashcard.objects.filter(
            Q(front__icontains=query) | Q(back__icontains=query)
        )[:50]
        flashcards_list = list(flashcards.values("id", "front", "back", "image"))
        for flashcard in flashcards_list:
            if flashcard["image"]:
                flashcard["image_url"] = default_storage.url(str(flashcard["image"]))
            else:
                flashcard["image_url"] = None

    return JsonResponse({"flashcards": flashcards_list})


@login_required
def search_students(request):
    query = request.GET.get("query", "")
    students_list = []
    if query:
        students = Student.objects.filter(user__username__icontains=query)[:50]
        for student in students:
            results = Result.objects.filter(student=student)

            new_cards = results.filter(state=Result.NEW_CARDS).count()
            still_learning = results.filter(state=Result.STILL_LEARNING).count()
            almost_done = results.filter(state=Result.ALMOST_DONE).count()
            mastered = results.filter(state=Result.MASTERED).count()

            all_flashcards = new_cards + still_learning + almost_done + mastered
            score = 0
            if all_flashcards > 0:
                score = int(
                    (still_learning / all_flashcards) * 25
                    + (almost_done / all_flashcards) * 75
                    + (mastered / all_flashcards) * 100
                )

            students_list.append({
                "user__id": student.user.id,
                "user__username": student.user.username,
                "score": score,
                "url": reverse("teachers:student", args=[student.user.id]),
            })

    return JsonResponse({"students": students_list})


@login_required
def search_decks(request):
    query = request.GET.get("query", "")
    decks_list = []
    if query:
        decks = Deck.objects.filter(name__icontains=query)[:50]
        decks_list = list(decks.values("id", "name", "teacher__user__username"))
        for deck in decks_list:
            deck["url"] = reverse("teachers:deck", args=[deck["id"]])

    return JsonResponse({"decks": decks_list})


@login_required
def student(request, id):
    student = Student.objects.get(user__id=id)
    results = Result.objects.filter(student=student)

    new_cards = results.filter(state=Result.NEW_CARDS).count()
    still_learning = results.filter(state=Result.STILL_LEARNING).count()
    almost_done = results.filter(state=Result.ALMOST_DONE).count()
    mastered = results.filter(state=Result.MASTERED).count()

    all_flashcards = new_cards + still_learning + almost_done + mastered
    score = 0
    if all_flashcards > 0:
        score = int(
            (still_learning / all_flashcards) * 25
            + (almost_done / all_flashcards) * 75
            + (mastered / all_flashcards) * 100
        )

    return render(
        request,
        "teachers/student.html",
        {
            "student": student,
            "results": results,
            "new_cards": new_cards,
            "still_learning": still_learning,
            "almost_done": almost_done,
            "mastered": mastered,
            "score": score,
        },
    )


@login_required
def student_data(request, id):
    student = Student.objects.get(user__id=id)
    results = Result.objects.filter(student=student)

    new_cards = results.filter(state=Result.NEW_CARDS).count()
    still_learning = results.filter(state=Result.STILL_LEARNING).count()
    almost_done = results.filter(state=Result.ALMOST_DONE).count()
    mastered = results.filter(state=Result.MASTERED).count()

    return JsonResponse({
        "new_cards": new_cards,
        "still_learning": still_learning,
        "almost_done": almost_done,
        "mastered": mastered,
    })


@login_required
def deck(request, id):
    deck = Deck.objects.get(id=id)
    flashcards = deck.flashcards.all()

    return render(
        request, "teachers/deck.html", {"deck": deck, "flashcards": flashcards}
    )


@login_required
def students(request):
    teacher = Teacher.objects.get(user=request.user)
    students = teacher.students.all()
    students_list = []

    for student in students:
        results = Result.objects.filter(student=student)

        new_cards = results.filter(state=Result.NEW_CARDS).count()
        still_learning = results.filter(state=Result.STILL_LEARNING).count()
        almost_done = results.filter(state=Result.ALMOST_DONE).count()
        mastered = results.filter(state=Result.MASTERED).count()

        all_flashcards = new_cards + still_learning + almost_done + mastered
        score = 0
        if all_flashcards > 0:
            score = int(
                (still_learning / all_flashcards) * 25
                + (almost_done / all_flashcards) * 75
                + (mastered / all_flashcards) * 100
            )

        student_dict = {
            "user__id": student.user.id,
            "user__username": student.user.username,
            "score": score
        }
        students_list.append(student_dict)

    return render(request, "teachers/students.html", {"students": students_list})


@login_required
def students_student(request):
    teacher = Teacher.objects.get(user=request.user)

    if request.method == "POST":
        student_id = request.POST.get("student_id")
        student = Student.objects.get(user__id=student_id)
        action = request.POST.get("action")

        if action == "add":
            teacher.add_student(student)
        elif action == "remove":
            teacher.remove_student(student)

    students = teacher.students.all()
    students_list = []

    for student in students:
        results = Result.objects.filter(student=student)

        new_cards = results.filter(state=Result.NEW_CARDS).count()
        still_learning = results.filter(state=Result.STILL_LEARNING).count()
        almost_done = results.filter(state=Result.ALMOST_DONE).count()
        mastered = results.filter(state=Result.MASTERED).count()

        all_flashcards = new_cards + still_learning + almost_done + mastered
        score = 0
        if all_flashcards > 0:
            score = int(
                (still_learning / all_flashcards) * 25
                + (almost_done / all_flashcards) * 75
                + (mastered / all_flashcards) * 100
            )

        student_dict = {
            "user__id": student.user.id,
            "user__username": student.user.username,
            "score": score
        }
        student_dict["url"] = reverse("teachers:student", args=[student_dict["user__id"]])
        students_list.append(student_dict)

    return JsonResponse({"students": students_list})


@login_required
def new_deck(request):
    if request.method == "POST":
        teacher = Teacher.objects.get(user=request.user)
        num_decks = Deck.objects.filter(teacher=teacher).count()
        deck = Deck(name=f"My Deck #{num_decks + 1}", teacher=teacher)
        deck.save()

        return redirect("teachers:deck", id=deck.id)


@login_required
def deck_flashcards(request, id):
    deck = Deck.objects.get(id=id)

    if request.method == "POST":
        flashcard_id = request.POST.get("flashcard_id")
        flashcard = Flashcard.objects.get(id=flashcard_id)
        action = request.POST.get("action")

        if action == "add":
            deck.add_flashcard(flashcard)
        elif action == "remove":
            deck.remove_flashcard(flashcard)

    flashcards = deck.flashcards.all()
    flashcards_list = list(flashcards.values("id", "front", "back", "image"))
    for flashcard in flashcards_list:
        if flashcard["image"]:
            flashcard["image_url"] = default_storage.url(str(flashcard["image"]))
        else:
            flashcard["image_url"] = None

    return JsonResponse({"flashcards": flashcards_list})

src/teachers/templates/teachers/assignment.html
{% extends "teachers/layout.html" %}

{% block title %}Flashcards - Assignment{% endblock %}

{% block main %}
    <h1>Assignment</h1>
    <h2>{{ request.user.username }}</h2>
    <table id="assignment-flashcards">
        <tbody>
            {% for flashcard in flashcards %}
                <tr>
                    <td class="image">
                        {% if flashcard.image %}
                            <img src="{{ flashcard.image.url }}" alt="Flashcard Image">
                        {% endif %}
                    </td>
                    <td class="front">{{ flashcard.front }}</td>
                    <td class="back">{{ flashcard.back }}</td>
                    <td class="checkbox"><input class="flashcard-checkbox" type="checkbox" data-flashcard-id="{{ flashcard.id }}" checked></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <input type="search" id="assignment-search" class="search" name="query" placeholder="Search flashcards" value="{{ query }}">
    <table id="search-results"></table>
{% endblock %}

src/teachers/templates/teachers/deck.html
{% extends "teachers/layout.html" %}

{% load static %}

{% block title %}{{ deck }} - deck by {{ request.user.username }} | Flashcards{% endblock %}

{% block main %}
    <h1>{{ deck }}</h1>
    <h2>{{ deck.teacher.user.username }}</h2>
    {% if request.user.username == deck.teacher.user.username %}
        <form method="POST" action="{% url 'teachers:edit_deck' deck.id %}">
            {% csrf_token %}
            <input type="text" id="deck-name" name="deck-name" placeholder="Add a name" required>
            <button type="submit">Save</button>
        </form>
        <form method="POST" action="{% url 'teachers:delete_deck' deck.id %}">
            {% csrf_token %}
            <button type="submit">Delete</button>
        </form>
    {% endif %}
    <table id="deck-flashcards">
        <tbody>
            {% for flashcard in flashcards %}
                <tr>
                    <td class="image">
                        {% if flashcard.image %}
                            <img src="{{ flashcard.image.url }}" alt="Flashcard Image">
                        {% endif %}
                    </td>
                    <td class="front">{{ flashcard.front }}</td>
                    <td class="back">{{ flashcard.back }}</td>
                    <td class="checkbox"><input type="checkbox" class="flashcard-checkbox" data-flashcard-id="{{ flashcard.id }}" {% if flashcard in teacher.flashcards.all %}checked{% endif %}></td>
                    {% if request.user.username == deck.teacher.user.username %}
                        <td class="button">
                            <button class="remove-button" data-flashcard-id="{{ flashcard.id }}"><img src="{% static 'teachers/close-outline.svg' %}" alt="Close Outline"></button>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if request.user.username == deck.teacher.user.username %}
        <input type="search" id="deck-search" class="search" name="query" placeholder="Search flashcards" value="{{ query }}">
        <table id="search-results"></table>
    {% endif %}
    <script>
        let deckFlashcardsUrl = "{% url 'teachers:deck_flashcards' deck.id %}";
        let closeOutlineSvg = "{% static 'teachers/close-outline.svg' %}";
    </script>
{% endblock %}

src/teachers/templates/teachers/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'teachers/favicon.ico' %}" rel="icon">
        <link href="{% static 'teachers/styles.css' %}" rel="stylesheet">
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
        <nav class="sidebar">
            <ul>
                <div class="menu-buttons">
                    <li>
                        <a href="{% url 'teachers:assignment' %}">
                            <span class="icon"><img src="{% static 'teachers/home-outline.svg' %}" alt="Home Outline"></span>
                            <span class="text">Assignment</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'teachers:search' %}">
                            <span class="icon"><img src="{% static 'teachers/search-outline.svg'%}" alt="Search Outline"></span>
                            <span class="text">Search</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'teachers:students' %}">
                            <span class="icon"><img src="{% static 'teachers/person-outline.svg' %}" alt="Person Outline"></span>
                            <span class="text">Students</span>
                        </a>
                    </li>
                </div>
                <div class="deck-container">
                    {% for deck in user_decks %}
                        <li>
                            <a href="{% url 'teachers:deck' deck.id %}" data-deck-id="{{ deck.id }}">
                                <span class="icon"><img src="{% static 'teachers/menu-outline.svg' %}" alt="Menu Outline"></span>
                                <span class="text">{{ deck }}</span>
                            </a>
                        </li>
                    {% endfor %}
                </div>
                <div class="bottom">
                    <form action="{% url 'teachers:new_deck' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">
                            <span class="icon"><img src="{% static 'teachers/add-outline.svg' %}" alt="Add Outline"></span>
                            <span class="text">New Deck</span>
                        </button>
                    </form>
                    <li>
                        <a href="{% url 'users:logout' %}">
                            <span class="icon"><img src="{% static 'teachers/log-out-outline.svg' %}" alt="Log Out Outline"></span>
                            <span class="text">Log Out</span>
                        </a>
                    </li>
                </div>
            </ul>
        </nav>

        <main>
            {% block main %}{% endblock %}
        </main>

        <script>
            let csrfToken = "{{ csrf_token }}";
            let assignmentFlashcardsUrl = "{% url 'teachers:assignment_flashcards' %}";
            let studentsStudentUrl = "{% url 'teachers:students_student' %}";
            let searchFlashcardsUrl = "{% url 'teachers:search_flashcards' %}";
            let searchStudentsUrl = "{% url 'teachers:search_students' %}";
            let searchDecksUrl = "{% url 'teachers:search_decks' %}";
        </script>
        <script src="{% static 'teachers/script.js' %}"></script>
    </body>

</html>

src/teachers/templates/teachers/search.html
{% extends "teachers/layout.html" %}

{% block title %}Flashcards - Search{% endblock %}

{% block main %}
    <input type="search" id="global-search" class="search" name="query" placeholder="Search" value="{{ query }}" autofocus>
    <div class="search-tabs">
        <button class="tab active" data-tab="all">All</button>
        <button class="tab" data-tab="flashcards">Flashcards</button>
        <button class="tab" data-tab="students">Students</button> 
        <button class="tab" data-tab="decks">Decks</button>
    </div>
    <table id="search-results-flashcards" class="results" data-category="flashcards"></table>
    <table id="search-results-students" class="results" data-category="students"></table>
    <table id="search-results-decks" class="results" data-category="decks"></table>
{% endblock %}

src/teachers/templates/teachers/student.html
{% extends "teachers/layout.html" %}

{% block title %}{{ student.user.username }} | Flashcards{% endblock %}

{% block main %}
    <h1>{{ student.user.username }}</h1>
    <ul class="progress-container">
        <li>
            <div id="studying-progress">Studying Progress</div>
            <div id="studying-progress-score" class="                                    
                                                    {% if score %}
                                                        {% if score < 25 %}score-low
                                                        {% elif score < 75 %}score-medium
                                                        {% elif score < 100 %}score-high
                                                        {% else %}score-perfect
                                                        {% endif %}
                                                    {% else %}
                                                        score-low
                                                    {% endif %}
                                                    ">{{ score }}%
            </div>
        </li>
        <li id="new-cards" class="score-low">
            <div>New Cards</div>
            <div>{{ new_cards }}</div>
        </li>
        <li id="still-learning" class="score-medium">
            <div>Still Learning</div>
            <div>{{ still_learning }}</div>
        </li>
        <li id="almost-done" class="score-high">
            <div>Almost Done</div>
            <div>{{ almost_done }}</div>
        </li>
        <li id="mastered" class="score-perfect">
            <div>Mastered</div>
            <div>{{ mastered }}</div>
        </li>
    </ul>
    <table>
        {% for result in results %}
            <tr>
                <td class="image">
                    {% if result.flashcard.image %}
                        <img src="{{ result.flashcard.image.url }}" alt="Flashcard Image">
                    {% endif %}
                </td>
                <td class="front">{{ result.flashcard.front }}</td>
                <td class="back">{{ result.flashcard.back }}</td>
                <td class="state">
                    <div class="
                                {% if result.state == 'New Cards' %}score-low
                                {% elif result.state == 'Still Learning' %}score-medium
                                {% elif result.state == 'Almost Done'%}score-high
                                {% else %}score-perfect
                                {% endif %}
                                ">
                        {{ result.state }}
                    </div>
                </td>
            </tr>
        {% endfor %}
    </table>
    <script>
        let studentDataUrl = "{% url 'teachers:student_data' student.user.id %}";
    </script>
{% endblock %}

src/teachers/templates/teachers/students.html
{% extends "teachers/layout.html" %}

{% block title %}Flashcards - Students{% endblock %}

{% block main %}
    <h1>Students</h1>
    <h2>{{ request.user.username }}</h2>
    <table id="students-student">
        <tbody>
            {% for student in students %}
                <tr>
                    <td class="name">{{ student.user__username }}</td>
                    <td class="score">
                        <div class="
                                    {% if student.score %}
                                        {% if student.score < 25 %}score-low
                                        {% elif student.score < 75 %}score-medium
                                        {% elif student.score < 100 %}score-high
                                        {% else %}score-perfect
                                        {% endif %}
                                    {% else %}
                                        score-low
                                    {% endif %}
                                   ">
                            {% if student.score %}
                                {{ student.score }}%
                            {% else %}
                                0%
                            {% endif %}
                        </div>
                    </td>
                    <td class="view-progress"><a href="{% url 'teachers:student' student.user__id %}">View Progress</a></td>
                    <td class="checkbox"><input type="checkbox" class="student-checkbox" data-student-id="{{ student.user__id }}" checked></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <input type="search" id="students-search" class="search" name="query" placeholder="Search students" value="{{ query }}">
    <table id="search-results"></table>
{% endblock %}