src/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/students/urls.py
from django.urls import path

from . import views

app_name = "students"
urlpatterns = [
    path("", views.index, name="index"),
    path("multiple_choice/", views.multiple_choice, name="multiple_choice"),
    path("true_false/", views.true_false, name="true_false"),
    path("writing/", views.writing, name="writing"),
    path("matching/", views.matching, name="matching"),
    path("get_flashcards/", views.get_flashcards, name="get_flashcards"),
    path("update_results/", views.update_results, name="update_results"),
    path("student_data/<int:id>/", views.student_data, name="student_data"),
]

src/users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

src/students/models.py
from django.db import models

# Create your models here.

src/students/views.py
from django.core.files.storage import default_storage
from django.http import JsonResponse
from django.shortcuts import render, redirect
import json

from users.models import Flashcard, Student, Teacher, Deck, Result


def login_required(view_func):
    def _wrapped_view(request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("users:login")
        elif request.session.get("role") == "teacher":
            return redirect("teachers:index")
        elif request.session.get("role") == "student":
            return view_func(request, *args, **kwargs)
        else:
            return redirect("users:index")

    return _wrapped_view


# Create your views here.
@login_required
def index(request):
    student = Student.objects.get(user=request.user)
    results = Result.objects.filter(student=student)

    new_cards = results.filter(state=Result.NEW_CARDS).count()
    still_learning = results.filter(state=Result.STILL_LEARNING).count()
    almost_done = results.filter(state=Result.ALMOST_DONE).count()
    mastered = results.filter(state=Result.MASTERED).count()

    all_flashcards = new_cards + still_learning + almost_done + mastered
    score = 0
    if all_flashcards > 0:
        score = int(
            (still_learning / all_flashcards) * 25
            + (almost_done / all_flashcards) * 75
            + (mastered / all_flashcards) * 100
        )

    return render(
        request,
        "students/index.html",
        {
            "student": student,
            "results": results,
            "new_cards": new_cards,
            "still_learning": still_learning,
            "almost_done": almost_done,
            "mastered": mastered,
            "score": score,
        },
    )


@login_required
def multiple_choice(request):
    return render(request, "students/multiple_choice.html")


@login_required
def true_false(request):
    return render(request, "students/true_false.html")


@login_required
def writing(request):
    return render(request, "students/writing.html")


@login_required
def matching(request):
    return render(request, "students/matching.html")


@login_required
def get_flashcards(request):
    student = Student.objects.get(user=request.user)
    results = Result.objects.filter(student=student)
    results_list = []

    for result in results:
        flashcard = result.flashcard
        results_list.append(
            {
                "flashcard__id": flashcard.id,
                "flashcard__front": flashcard.front,
                "flashcard__back": flashcard.back,
                "flashcard__image": default_storage.url(str(flashcard.image)),
                "state": result.state,
            }
        )

    return JsonResponse({"flashcards": results_list})


@login_required
def update_results(request):
    student = Student.objects.get(user=request.user)

    if request.method == "POST":
        flashcards = json.loads(request.body).get("flashcards")

        for flashcard_data in flashcards:
            try:
                flashcard = Flashcard.objects.get(id=flashcard_data["flashcard__id"])
                result = Result.objects.get(student=student, flashcard=flashcard)
                result.state = flashcard_data["state"]
                result.save()
            except Result.DoesNotExist:
                continue

    return JsonResponse({"message": "Results updated successfully."})


@login_required
def student_data(request, id):
    student = Student.objects.get(user=request.user)
    results = Result.objects.filter(student=student)

    new_cards = results.filter(state=Result.NEW_CARDS).count()
    still_learning = results.filter(state=Result.STILL_LEARNING).count()
    almost_done = results.filter(state=Result.ALMOST_DONE).count()
    mastered = results.filter(state=Result.MASTERED).count()

    return JsonResponse({
        "new_cards": new_cards,
        "still_learning": still_learning,
        "almost_done": almost_done,
        "mastered": mastered,
    })

src/students/templates/students/index.html
{% extends "students/layout.html" %}

{% load static %}

{% block title %}Flashcards{% endblock %}

{% block body %}
    <nav>
        <h1>{{ student.user.username }}</h1>
        <a href="{% url 'students:multiple_choice' %}">📚 Multiple Choice</a>
        <a href="{% url 'students:true_false' %}">✅ True False</a>
        <a href="{% url 'students:writing' %}">✏️ Writing</a>
        <a href="{% url 'students:matching' %}">🧩 Matching</a>
        <a href="{% url 'users:logout' %}">Log Out</a>
    </nav>

    <main>
        <ul class="progress-container">
            <li>
                <div id="studying-progress">Studying Progress</div>
                <div id="studying-progress-score" class="                                    
                                                        {% if score %}
                                                            {% if score < 25 %}score-low
                                                            {% elif score < 75 %}score-medium
                                                            {% elif score < 100 %}score-high
                                                            {% else %}score-perfect
                                                            {% endif %}
                                                        {% else %}
                                                            score-low
                                                        {% endif %}
                                                        ">{{ score }}%
                </div>
            </li>
            <li id="new-cards" class="score-low">
                <div>New Cards</div>
                <div>{{ new_cards }}</div>
            </li>
            <li id="still-learning" class="score-medium">
                <div>Still Learning</div>
                <div>{{ still_learning }}</div>
            </li>
            <li id="almost-done" class="score-high">
                <div>Almost Done</div>
                <div>{{ almost_done }}</div>
            </li>
            <li id="mastered" class="score-perfect">
                <div>Mastered</div>
                <div>{{ mastered }}</div>
            </li>
        </ul>
        <table>
            {% for result in results %}
                <tr>
                    <td class="image">
                        {% if result.flashcard.image %}
                            <img src="{{ result.flashcard.image.url }}" alt="Flashcard Image">
                        {% endif %}
                    </td>
                    <td class="front">{{ result.flashcard.front }}</td>
                    <td class="back">{{ result.flashcard.back }}</td>
                    <td class="state">
                        <div class="
                                    {% if result.state == 'New Cards' %}score-low
                                    {% elif result.state == 'Still Learning' %}score-medium
                                    {% elif result.state == 'Almost Done'%}score-high
                                    {% else %}score-perfect
                                    {% endif %}
                                    ">
                            {{ result.state }}
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </main>
    <script>
        let studentDataUrl = "{% url 'students:student_data' student.user.id %}";
    </script>
    <script src="{% static 'students/index.js' %}"></script>
{% endblock %}

src/students/templates/students/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'students/favicon.ico' %}" rel="icon">
        <link href="{% static 'students/styles.css' %}" rel="stylesheet">
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
        {% block body %}{% endblock %}
    </body>

</html>

src/students/templates/students/matching.html
{% extends "students/layout.html" %}

{% block title %}Flashcards - Matching{% endblock %}

{% block body %}
    <div>not implement</div>
{% endblock %}

src/students/templates/students/multiple_choice.html
{% extends "students/layout.html" %}

{% load static %}

{% block title %}Flashcards - Multiple Choice{% endblock %}

{% block body %}
    <main>
        <progress class="progress-bar" value="0" max="7"></progress>
        <div class="question-container">
            <div class="top-half">
                <div class="multiple-choice-question"></div>
                <img alt="Flashcard image"></img>
            </div>
            <div class="bottom-half">
                <div class="multiple-choice-label">Select the matching term</div>
                <div class="multiple-choice-answer">
                    <button id="answer1" class="answer"></button>
                    <button id="answer2" class="answer"></button>
                    <button id="answer3" class="answer"></button>
                    <button id="answer4" class="answer"></button>
                </div>
            </div>
        </div>
    </main>

    <script>
        let csrfToken = "{{ csrf_token }}";
        let getFlashcardsUrl = "{% url 'students:get_flashcards' %}";
        let updateResultsUrl = "{% url 'students:update_results' %}";
        let indexUrl = "{% url 'students:index' %}";
        let multipleChoiceUrl = "{% url 'students:multiple_choice' %}";
    </script>
    <script src="{% static 'students/multiple_choice.js' %}"></script>
{% endblock %}

src/students/templates/students/true_false.html
{% extends "students/layout.html" %}

{% block title %}Flashcards - True/False{% endblock %}

{% block body %}
    <div>not implement</div>
{% endblock %}

src/students/templates/students/writing.html
{% extends "students/layout.html" %}

{% block title %}Flashcards - Writing{% endblock %}

{% block body %}
    <div>not implement</div>
{% endblock %}